% Preprocess EEG for the song familiarity project
% 
% Other m-files required: 
% EEGLAB toolbox https://github.com/sccn/eeglab
% /private/dm_prep.m
% /private/dmlab31.locs
% /private/dmlab33.locs

% Author: Cameron Hassall, Department of Psychology, MacEwan University
% email address: hassallc@macewan.ca
% Website: http://www.cameronhassall.com

% Participant strings
eeglab(); close all; clear all; clc;
init_unfold();
ps = {'sub-01','sub-02','sub-03','sub-04','sub-05','sub-06','sub-07','sub-09','sub-10','sub-11','sub-12','sub-13','sub-14','sub-15','sub-16','sub-17','sub-18','sub-19','sub-20','sub-21','sub-22','sub-23','sub-24','sub-25','sub-26','sub-27','sub-28','sub-29','sub-30'}; % No EEG for 08

% Set data folders - set as needed
if ispc
    dataFolder = 'F:\2024_EEG_SongFamiliarity_Hassall\bids';
else
    dataFolder = '/Volumes/T7 (Data)/2024_EEG_SongFamiliarity_Hassall/bids';
end

% ICA settings - which triggers? Window size?
icaTriggers = {'1'}; % Start of song
icaWindow = [0 10]; % Ten seconds
icaTriggers = []; % Start of song
icaWindow = []; % Ten seconds
filters = [0.1 20];

% Electrodes to interpolate
toRemove = {'sub-01', {};...
        'sub-02',{};...
        'sub-03', {'O1'};...
        'sub-04',{};...
        'sub-05', {'CP1'};...
        'sub-06',{};...
        'sub-07', {};...
        'sub-09',{};...
        'sub-10', {};...
        'sub-11',{'F7'};...
        'sub-12', {};...
        'sub-13',{};...
        'sub-14', {};...
        'sub-15',{};...
        'sub-16', {};...
        'sub-17',{'Fp1','Fp2'};...
        'sub-18',{};...
        'sub-19', {};...
        'sub-20',{};...
        'sub-21', {};...
        'sub-22',{};...
        'sub-23', {};...
        'sub-24',{'P8'};...
        'sub-25', {'Fp1','Fp2'};...
        'sub-26',{};...
        'sub-27', {};...
        'sub-28',{};...
        'sub-29', {};...
        'sub-30',{}};

disp('Removed channels (M,SD):')
disp(mean(cellfun(@length,toRemove(:,2))));
disp(std(cellfun(@length,toRemove(:,2))));

reference = {'TP9','TP10'};
appendString = '';
exportAsBV = 0;

% Loop through participants
for p = 1:length(subjStrs)
    rng('default'); rng(2024); % Set for consistency
    subName = ps{p};
    taskName = 'songfamiliarity';
    badChannelsI = find(strcmp(ps{p},{toRemove{:,1}}));
    badChannels = toRemove{badChannelsI,2};
    dm_prep(dataFolder,subName,taskName,icaTriggers,icaWindow,filters,reference,badChannels,appendString,exportAsBV);
end

%%Check how many ICs were removed
numICS = [];
for p = 1:length(ps)
    subName = ps{p};
    taskName = 'songfamiliarity';
    prepFile = [subName '_task-' taskName '_eegprep.mat'];
    prepFolder =  fullfile(dataFolder,subName, 'derivatives','eegprep');
    load(fullfile(prepFolder,prepFile),'EEG');
    numICS(p) = size(EEG.icaweights,2)- size(EEG.icaweights,1);
end
disp(mean(numICS));
disp(std(numICS));